---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/shell"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/shell"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

# Hack needed for s390x: https://gist.github.com/colstrom/c2f359f72658aaabb44150ac20b16d7c#gistcomment-3858388
node:
  arch: s390x

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: rancher/drone-images:docker-s390x
  volumes:
    - name: docker
      path: /var/run/docker.sock
  settings:
    build_args:
    - ARCH=s390x
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/shell"
    tag: "${DRONE_TAG}-s390x"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
    target: "rancher/shell:${DRONE_TAG}"
    template: "rancher/shell:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64
- arm64
- s390x

---
kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    when:
      instance:
        - drone-publish.rancher.io
