---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/shell"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/shell"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.4.0
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "rancher/shell:${DRONE_TAG}"
    template: "rancher/shell:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

depends_on:
- amd64
- arm64

