#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts

IMAGE=${REPO}/shell:${TAG}
DOCKERFILE=package/Dockerfile

docker build -f ${DOCKERFILE} -t ${IMAGE} --build-arg ARCH=${ARCH} .
echo Built ${IMAGE}
