#!/bin/sh
set -e

sleep 1
for i in $(seq 1 20); do
    if kubectl version >/dev/null 2>&1; then
        break
    fi
    echo Waiting for Kubernetes API to be available
    if [ $i = 20 ]; then
        echo Timeout waiting for kubernetes
        exit 1
    fi
    sleep 1
done

for i in operation*; do
    cat $i | xargs -0 -- echo helm
    cat $i | xargs -0 -- helm
    echo
    echo '---------------------------------------------------------------------'
    cat $i | xargs -0 -- echo SUCCESS: helm
    echo '---------------------------------------------------------------------'
done
