name: FOSSA Scanning

on:
  push:
    branches: ["main", "master", "release/**"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  fossa-scanning:
    uses: rancher/shell/.github/workflows/fossa.yml@automation-core
