name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: rancher/shell/.github/workflows/release.yml@automation-core
    secrets: inherit
