name: Tests

on:
  push:
    branches:
      - master
      - release/v2.*
  pull_request:

permissions:
  contents: read

jobs:
  call-workflow:
    uses: rancher/shell/.github/workflows/tests.yml@automation-core
