name: Tests

on:
  push:
    branches:
      - master
      - release/v2.*
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/charts
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - run: make validate

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/charts
    needs: [ validate ]
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
  
    - run: make test
